/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.pintameeltecho.view.panels;

import java.awt.event.ActionListener;

/**
 *
 * @author Carlos
 */
public class ButtonsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ButtonsPanel
     */
    public ButtonsPanel() {
        initComponents();
    }
    
    public void listen(ActionListener controller){
        btnAdd.addActionListener(controller);
        btnDelete.addActionListener(controller);
        btnEdit.addActionListener(controller);
        btnMenu.addActionListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonAddMantenace.png"))); // NOI18N
        btnAdd.setActionCommand("Agregar");
        btnAdd.setBorder(null);
        btnAdd.setContentAreaFilled(false);
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonEditarMantenace.png"))); // NOI18N
        btnEdit.setActionCommand("Editar");
        btnEdit.setBorder(null);
        btnEdit.setBorderPainted(false);
        btnEdit.setContentAreaFilled(false);
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonBorrarMantenace.png"))); // NOI18N
        btnDelete.setActionCommand("Eliminar");
        btnDelete.setBorder(null);
        btnDelete.setBorderPainted(false);
        btnDelete.setContentAreaFilled(false);
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonHomeMantenace.png"))); // NOI18N
        btnMenu.setToolTipText("");
        btnMenu.setActionCommand("Menu");
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setContentAreaFilled(false);
        add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MantenaceUsers_1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 140));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
