/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.pintameeltecho.view.panels;

import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class DataTable extends javax.swing.JPanel {

    /**
     * Creates new form UserData
     */
    public DataTable() {
        initComponents();
    }
    
    public void listenMouse(MouseListener controller){
        tblUsersData.addMouseListener(controller);
    }
    
    public void listenKeyBoard(KeyListener controller){
        txtFilter.addKeyListener(controller);
    }
    
    public void setData(String[][]data, String[]labels){
        DefaultTableModel model= new DefaultTableModel(data, labels);
        tblUsersData.setModel(model);
        tblUsersData.setRowSorter(new TableRowSorter<>(model));
        jScrollPane1.setViewportView(tblUsersData);
    }

    public void filterByMail(){
        DefaultTableModel model=(DefaultTableModel)tblUsersData.getModel();
        TableRowSorter<DefaultTableModel> sorter=new TableRowSorter<>(model);
        tblUsersData.setRowSorter(sorter);
        String txtFilterMail= txtFilter.getText();
        if (txtFilterMail.length()==0) {
            sorter.setRowFilter(null);
            tblUsersData.clearSelection();
        }else{
            sorter.setRowFilter(RowFilter.regexFilter(txtFilterMail, 0));
        }
    }
    
    public String [] getRowSelected(){
        int rowSelected= tblUsersData.getSelectedRow();
        String [] rowData = new String[tblUsersData.getColumnCount()];
        if (rowSelected!=-1) {
            for (int column = 0; column < rowData.length; column++) {
                rowData[column]=tblUsersData.getValueAt(rowSelected, column).toString();
            }
            return rowData;
        }
        return new String[0];
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsersData = new javax.swing.JTable();
        txtFilter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblUsersData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsersData);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 550, 370));

        txtFilter.setBackground(new java.awt.Color(238, 228, 255));
        txtFilter.setBorder(null);
        add(txtFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 21, 230, 29));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MantenaceUsers_1.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsersData;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
