/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.pintameeltecho.view.panels;

import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Admin
 */
public class DataTable extends javax.swing.JPanel {

    /**
     * Creates new form UserData
     */
    public DataTable() {
        initComponents();
    }
    
    public void listenMouse(MouseListener controller){
        tblUsersData.addMouseListener(controller);
    }
    
    public void listenKeyBoard(KeyListener controller){
        txtFilter.addKeyListener(controller);
    }
    
    public void setData(String[][]data, String[]labels){
        DefaultTableModel model= new DefaultTableModel(data, labels);
        tblUsersData.setModel(model);
        tblUsersData.setRowSorter(new TableRowSorter<>(model));
        jScrollPane1.setViewportView(tblUsersData);
    }

    public void filterByMail(){
        DefaultTableModel model=(DefaultTableModel)tblUsersData.getModel();
        TableRowSorter<DefaultTableModel> sorter=new TableRowSorter<>(model);
        tblUsersData.setRowSorter(sorter);
        String txtFilterMail= txtFilter.getText();
        if (txtFilterMail.length()==0) {
            sorter.setRowFilter(null);
            tblUsersData.clearSelection();
        }else{
            sorter.setRowFilter(RowFilter.regexFilter(txtFilterMail, 0));
        }
    }
    
    public String [] getRowSelected(){
        int rowSelected= tblUsersData.getSelectedRow();
        String [] rowData = new String[tblUsersData.getColumnCount()];
        if (rowSelected!=-1) {
            for (int column = 0; column < rowData.length; column++) {
                rowData[column]=tblUsersData.getValueAt(rowSelected, column).toString();
            }
            return rowData;
        }
        return new String[0];
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsersData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();

        tblUsersData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsersData);

        jLabel1.setText("Filtro por correo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtFilter)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsersData;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
