/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.pintameeltecho.view.service;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class GUIReview extends javax.swing.JFrame {

    /**
     * Creates new form GUIReview
     */
    public GUIReview() {
        initComponents();
    }

    public void listen(ActionListener controller){
        btnStar1.addActionListener(controller);
        btnStar2.addActionListener(controller);
        btnStar3.addActionListener(controller);
        btnStar4.addActionListener(controller);
        btnStar5.addActionListener(controller);
        btnSave.addActionListener(controller);
        btnExit.addActionListener(controller);
    }

    public void listenMouse(MouseListener controller){
        btnStar1.addMouseListener(controller);
        btnStar2.addMouseListener(controller);
        btnStar3.addMouseListener(controller);
        btnStar4.addMouseListener(controller);
        btnStar5.addMouseListener(controller);
    }
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(null, message);
    }
    

    public String getTxtReview() {
        return txtReview.getText();
    }

    public void setTxtReview(String txtReview) {
        this.txtReview.setText(txtReview);
    }

    public JButton getBtnStar1() {
        return btnStar1;
    }

    public void setBtnStar1(String btnStar1) {
        this.btnStar1.setIcon(new ImageIcon (btnStar1));
    }

    public JButton getBtnStar2() {
        return btnStar2;
    }

    public void setBtnStar2(String btnStar2) {
        this.btnStar2.setIcon(new ImageIcon (btnStar2));
    }

    public JButton getBtnStar3() {
        return btnStar3;
    }

    public void setBtnStar3(String btnStar3) {
        this.btnStar3.setIcon(new ImageIcon (btnStar3));
    }

    public JButton getBtnStar4() {
        return btnStar4;
    }

    public void setBtnStar4(String btnStar4) {
        this.btnStar4.setIcon(new ImageIcon (btnStar4));
    }

    public JButton getBtnStar5() {
        return btnStar5;
    }

    public void setBtnStar5(String btnStar5) {
        this.btnStar5.setIcon(new ImageIcon (btnStar5));
    }
    
    public void clean(){
        setTxtReview("");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStar1 = new javax.swing.JButton();
        btnStar2 = new javax.swing.JButton();
        btnStar3 = new javax.swing.JButton();
        btnStar4 = new javax.swing.JButton();
        btnStar5 = new javax.swing.JButton();
        txtReview = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonEmptyStar.png"))); // NOI18N
        btnStar1.setActionCommand("Star1");
        btnStar1.setBorder(null);
        btnStar1.setBorderPainted(false);
        btnStar1.setContentAreaFilled(false);
        getContentPane().add(btnStar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        btnStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonEmptyStar.png"))); // NOI18N
        btnStar2.setActionCommand("Star2");
        btnStar2.setBorder(null);
        btnStar2.setBorderPainted(false);
        btnStar2.setContentAreaFilled(false);
        getContentPane().add(btnStar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));

        btnStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonEmptyStar.png"))); // NOI18N
        btnStar3.setActionCommand("Star3");
        btnStar3.setBorder(null);
        btnStar3.setBorderPainted(false);
        btnStar3.setContentAreaFilled(false);
        getContentPane().add(btnStar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, -1, -1));

        btnStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonEmptyStar.png"))); // NOI18N
        btnStar4.setActionCommand("Star4");
        btnStar4.setBorder(null);
        btnStar4.setBorderPainted(false);
        btnStar4.setContentAreaFilled(false);
        getContentPane().add(btnStar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        btnStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonEmptyStar.png"))); // NOI18N
        btnStar5.setActionCommand("Star5");
        btnStar5.setBorder(null);
        btnStar5.setBorderPainted(false);
        btnStar5.setContentAreaFilled(false);
        getContentPane().add(btnStar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 430, -1, -1));

        txtReview.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtReview.setForeground(new java.awt.Color(11, 22, 66));
        txtReview.setBorder(null);
        getContentPane().add(txtReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 650, 120));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonCancel.png"))); // NOI18N
        btnExit.setActionCommand("SalirReview");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, -1, -1));

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonAcept.png"))); // NOI18N
        btnSave.setActionCommand("Guardar");
        btnSave.setBorder(null);
        btnSave.setBorderPainted(false);
        btnSave.setContentAreaFilled(false);
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ReviewPage.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStar1;
    private javax.swing.JButton btnStar2;
    private javax.swing.JButton btnStar3;
    private javax.swing.JButton btnStar4;
    private javax.swing.JButton btnStar5;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField txtReview;
    // End of variables declaration//GEN-END:variables
}
