/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.pintameeltecho.view.service;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class GUIServiceRegister extends javax.swing.JFrame {

    /**
     * Creates new form GUIServiceRegister
     */
    public GUIServiceRegister() {
        initComponents();
    }

    public void listen(ActionListener controller) {
        btnRegister.addActionListener(controller);
        btnCancel.addActionListener(controller);
        btnArt.addActionListener(controller);
        btnGarden.addActionListener(controller);
        btnReparation.addActionListener(controller);
    }

    public String getTxtAproximatePrice() {
        return txtAproximatePrice.getText();
    }

    public String getTxtDescription() {
        return txtDescription.getText();
    }

    public String getTxtName() {
        return txtName.getText();
    }

    public void setTxtAproximatePrice(String txtAproximatePrice) {
        this.txtAproximatePrice.setText(txtAproximatePrice);
    }

    public void setTxtDescription(String txtDescription) {
        this.txtDescription.setText(txtDescription);
    }

    public void setTxtName(String txtName) {
        this.txtName.setText(txtName);
    }

    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(null, message);
    }
    
    public void clean(){
        setTxtAproximatePrice("");
        setTxtDescription("");
        setTxtName("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtName = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        txtAproximatePrice = new javax.swing.JTextField();
        btnArt = new javax.swing.JButton();
        btnReparation = new javax.swing.JButton();
        btnGarden = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(11, 22, 66));
        txtName.setBorder(null);
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 202, 330, 38));

        txtDescription.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(11, 22, 66));
        txtDescription.setBorder(null);
        getContentPane().add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 300, 96));

        txtAproximatePrice.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtAproximatePrice.setForeground(new java.awt.Color(11, 22, 66));
        txtAproximatePrice.setBorder(null);
        getContentPane().add(txtAproximatePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 478, 280, 33));

        btnArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonIconPintura.png"))); // NOI18N
        btnArt.setActionCommand("Arte");
        btnArt.setBorder(null);
        btnArt.setBorderPainted(false);
        btnArt.setContentAreaFilled(false);
        getContentPane().add(btnArt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 260, -1, 160));

        btnReparation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonIconReparacion.png"))); // NOI18N
        btnReparation.setActionCommand("Reparaciones");
        btnReparation.setBorder(null);
        btnReparation.setBorderPainted(false);
        btnReparation.setContentAreaFilled(false);
        getContentPane().add(btnReparation, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, 190, 160));

        btnGarden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonIconJardineria.png"))); // NOI18N
        btnGarden.setActionCommand("Jardin");
        btnGarden.setBorder(null);
        btnGarden.setBorderPainted(false);
        btnGarden.setContentAreaFilled(false);
        getContentPane().add(btnGarden, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 260, -1, 160));

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonAcept.png"))); // NOI18N
        btnRegister.setActionCommand("Registrar");
        btnRegister.setBorder(null);
        btnRegister.setBorderPainted(false);
        btnRegister.setContentAreaFilled(false);
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 119, 100));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonCancel.png"))); // NOI18N
        btnCancel.setActionCommand("Cancelar");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 630, 120, 110));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PageServiceRegister.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArt;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGarden;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnReparation;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAproximatePrice;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
