/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.pintameeltecho.view.service;

import java.awt.event.KeyListener;
import java.awt.event.MouseListener;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author paulz
 */
public class ServiceTable extends javax.swing.JPanel {

    /**
     * Creates new form ServiceTable
     */
    public ServiceTable() {
        initComponents();
    }
    public void listenMouse(MouseListener controller) {
        tblServices.addMouseListener(controller);
    }
    
    public void listenKey (KeyListener controller){
        txtSearch.addKeyListener(controller);
    }
    
    public void filterByName (){
        DefaultTableModel model= (DefaultTableModel) tblServices.getModel();
        TableRowSorter<DefaultTableModel> sorter= new TableRowSorter<>(model);
        tblServices.setRowSorter(sorter);
        String txtFilterId=txtSearch.getText();
        if(txtFilterId.length()==0){
            sorter.setRowFilter(null);
            tblServices.clearSelection();
        }else{
            sorter.setRowFilter(RowFilter.regexFilter(txtFilterId,0));
        }
    }
    
    public void setData(String[][] data, String[] labels) {
        DefaultTableModel model = new DefaultTableModel(data, labels);
        tblServices.setModel(model);
        tblServices.setRowSorter(new TableRowSorter<>(model));
        jScrollPane1.setViewportView(tblServices);

    }
    public String[] getRowSelected() {
        int rowSelected = tblServices.getSelectedRow();
        String[] rowData = new String[tblServices.getColumnCount()];
        if (rowSelected != -1) {
            for(int column=0;column<rowData.length;column++){
                rowData[column]=tblServices.getValueAt(rowSelected, column).toString();
            }
            return rowData;
        }
        return new String[0];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblServices = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblServices);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 988, 532));

        txtSearch.setBackground(new java.awt.Color(238, 228, 255));
        txtSearch.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(11, 22, 66));
        txtSearch.setToolTipText("");
        txtSearch.setBorder(null);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 24, 360, 45));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MainPage.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 780));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblServices;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
