/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ucr.ac.cr.pintameeltecho.view.page;

import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Carlos
 */
public class GUIInfoService extends javax.swing.JDialog {

    /**
     * Creates new form GUIInfoService
     */
    public GUIInfoService(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void listen(ActionListener controller){
        btnCancelContract.addActionListener(controller);
        btnContract.addActionListener(controller);
    }

    public void setjLabelDescrip(JLabel jLabelDescrip) {
        this.jLabelDescrip = jLabelDescrip;
    }

    public void setjLabelSocioN(JLabel jLabelSocioN) {
        this.jLabelSocioN = jLabelSocioN;
    }

    public void setjLabelTitle(JLabel jLabelTitle) {
        this.jLabelTitle = jLabelTitle;
    }

    public void setJlabelIcon(String icon) {
        this.jlabelIcon.setIcon(new ImageIcon(icon));
    }

    public JLabel getjLabelDescrip() {
        return jLabelDescrip;
    }

    public JLabel getjLabelSocioN() {
        return jLabelSocioN;
    }

    public JLabel getjLabelTitle() {
        return jLabelTitle;
    }

    public JLabel getJlabelIcon() {
        return jlabelIcon;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnContract = new javax.swing.JButton();
        btnCancelContract = new javax.swing.JButton();
        jLabelSocioN = new javax.swing.JLabel();
        jLabelDescrip = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jlabelIcon = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnContract.setText("Contratar");
        btnContract.setActionCommand("Hire");
        getContentPane().add(btnContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 660, -1, -1));

        btnCancelContract.setText("Cancelar");
        btnCancelContract.setActionCommand("Cancel");
        getContentPane().add(btnCancelContract, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 660, -1, -1));

        jLabelSocioN.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelSocioN.setForeground(new java.awt.Color(28, 42, 87));
        jLabelSocioN.setText("Ricardo Perez Araya ");
        getContentPane().add(jLabelSocioN, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabelDescrip.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelDescrip.setForeground(new java.awt.Color(28, 42, 87));
        jLabelDescrip.setText("<html>Ofrezco servicio de pintura de techos para casas, comercios e industrias, incluyendo limpieza, preparación de superficies, aplicación de selladores y pintura impermeabilizante. Trabajo con materiales de alta calidad para proteger tu techo contra filtraciones, hongos y desgaste, garantizando un acabado duradero y profesional. Presupuestos sin compromiso, atención puntual y mano de obra responsable. ¡Consulta y dale nueva vida a tu techo!</html> ");
        jLabelDescrip.setToolTipText("");
        jLabelDescrip.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 660, 280));

        jLabelTitle.setBackground(new java.awt.Color(0, 0, 0));
        jLabelTitle.setFont(new java.awt.Font("Eras Demi ITC", 1, 54)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(28, 42, 87));
        jLabelTitle.setText("Texto de prueba");
        getContentPane().add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 650, 100));

        jlabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IconPaint.png"))); // NOI18N
        getContentPane().add(jlabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 360, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoServicio.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelContract;
    private javax.swing.JButton btnContract;
    private javax.swing.JLabel jLabelDescrip;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelSocioN;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jlabelIcon;
    // End of variables declaration//GEN-END:variables
}
