/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.pintameeltecho.view.user;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class GUIRegistration extends javax.swing.JFrame {

    /**
     * Creates new form GUIRegistration
     */
    public GUIRegistration() {
        initComponents();
    }

    
    public void listen(ActionListener controller) {
        btnRegister.addActionListener(controller);
        btnCancel.addActionListener(controller);
    }

    public String getJcbRol() {
        return jcbRol.getSelectedItem().toString();
    }

    public void setJcbRol(String jcbRol) {
        this.jcbRol.setSelectedItem(jcbRol);
    }

    public String getTxtDirection() {
        return txtDirection.getText();
    }

    public void setTxtDirection(String txtDirection) {
        this.txtDirection.setText(txtDirection);
    }

    public String getTxtMail() {
        return txtMail.getText();
    }

    public void setTxtMail(String txtMail) {
        this.txtMail.setText(txtMail);
    }

    public String getTxtName() {
        return txtName.getText();
    }

    public void setTxtName(String txtName) {
        this.txtName.setText(txtName);
    }

    public String getTxtPassword() {
        return txtPassword.getText();
    }

    public void setTxtPassword(String txtPassword) {
        this.txtPassword.setText(txtPassword);
    }

    public String getTxtPasswordAgain() {
        return txtPasswordAgain.getText();
    }

    public void setTxtPasswordAgain(String txtPasswordAgain) {
        this.txtPasswordAgain.setText(txtPasswordAgain);
    }
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(null, message);
    }
    
    public void clean(){
        setTxtMail("");
        setTxtName("");
        setTxtDirection("");
        setTxtPassword("");
        setTxtPasswordAgain("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRol = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtDirection = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtPasswordAgain = new javax.swing.JTextField();
        jcbRol = new javax.swing.JComboBox<>();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRol.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        lblRol.setForeground(new java.awt.Color(11, 22, 66));
        lblRol.setText("Rol:");
        getContentPane().add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        txtMail.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtMail.setForeground(new java.awt.Color(11, 22, 66));
        txtMail.setBorder(null);
        getContentPane().add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 205, 330, 35));

        txtName.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtName.setForeground(new java.awt.Color(11, 22, 66));
        txtName.setBorder(null);
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 287, 280, 35));

        txtDirection.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtDirection.setForeground(new java.awt.Color(11, 22, 66));
        txtDirection.setBorder(null);
        getContentPane().add(txtDirection, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 224, 290, 94));

        txtPassword.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(11, 22, 66));
        txtPassword.setBorder(null);
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 398, 280, 34));

        txtPasswordAgain.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtPasswordAgain.setForeground(new java.awt.Color(11, 22, 66));
        txtPasswordAgain.setBorder(null);
        getContentPane().add(txtPasswordAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 476, 280, 34));

        jcbRol.setBackground(new java.awt.Color(249, 249, 252));
        jcbRol.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jcbRol.setForeground(new java.awt.Color(11, 22, 66));
        jcbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Socio" }));
        getContentPane().add(jcbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 130, 50));

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonAcept.png"))); // NOI18N
        btnRegister.setActionCommand("Registrar");
        btnRegister.setBorder(null);
        btnRegister.setBorderPainted(false);
        btnRegister.setContentAreaFilled(false);
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, -1, -1));

        btnCancel.setForeground(new java.awt.Color(234, 234, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonCancel.png"))); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.setBorder(null);
        btnCancel.setBorderPainted(false);
        btnCancel.setContentAreaFilled(false);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 600, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RegisterUserPage.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jcbRol;
    private javax.swing.JLabel lblRol;
    private javax.swing.JTextField txtDirection;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPasswordAgain;
    // End of variables declaration//GEN-END:variables
}
