/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.pintameeltecho.view.user;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import ucr.ac.cr.pintameeltecho.view.panels.DataTable;

/**
 *
 * @author Carlos
 */
public class GUIUserMaintenance extends javax.swing.JFrame {

    /**
     * Creates new form UserMaintenance
     */
    public GUIUserMaintenance(ActionListener controller) {
        initComponents();
        buttonsPanel.listen(controller);
    }
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(null, message);
    }

    public DataTable getDataTable() {
        return dataTable;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new ucr.ac.cr.pintameeltecho.view.panels.ButtonsPanel();
        dataTable = new ucr.ac.cr.pintameeltecho.view.panels.DataTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(buttonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));
        getContentPane().add(dataTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.pintameeltecho.view.panels.ButtonsPanel buttonsPanel;
    private ucr.ac.cr.pintameeltecho.view.panels.DataTable dataTable;
    // End of variables declaration//GEN-END:variables
}
