/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.pintameeltecho.view;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import ucr.ac.cr.pintameeltecho.controller.userController.UserController;

/**
 *
 * @author Admin
 */
public class GUIMain extends javax.swing.JFrame {
    private UserController controller;
    
    /**
     * Creates new form GUIMain
     */
    public GUIMain() {
        initComponents();
        
    }

    public String getTxtLogInUser() {
        return txtLogInUser.getText();
    }

    public void setTxtLogInUser(String txtLogInUser) {
        this.txtLogInUser.setText(txtLogInUser);
    }

    public String getTxtLogInPassw() {
        return txtLogInPassw.getText();
    }

    public void setTxtLogInPassw(String txtLogInPassw) {
        this.txtLogInPassw.setText(txtLogInPassw);
    }
    



    public void listen(ActionListener controller) {
        btnRegister.addActionListener(controller);
        btnLogin.addActionListener(controller);
        btnExit.addActionListener(controller);
    }
    
    public void showMessage(String message){
        JOptionPane.showMessageDialog(null, message);
    }
    
    public void clean(){
        setTxtLogInUser("");
        setTxtLogInPassw("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtLogInUser = new javax.swing.JTextField();
        txtLogInPassw = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonCrear.png"))); // NOI18N
        btnRegister.setActionCommand("Registrarse");
        btnRegister.setBorder(null);
        btnRegister.setBorderPainted(false);
        btnRegister.setContentAreaFilled(false);
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 650, 179, -1));

        btnLogin.setBackground(new java.awt.Color(153, 204, 255));
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonIngresar.png"))); // NOI18N
        btnLogin.setActionCommand("Ingresar");
        btnLogin.setBorder(null);
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 160, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ButtonSalir.png"))); // NOI18N
        btnExit.setActionCommand("Salir");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setFocusPainted(false);
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 110, 100));

        txtLogInUser.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtLogInUser.setForeground(new java.awt.Color(11, 22, 66));
        txtLogInUser.setBorder(null);
        getContentPane().add(txtLogInUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 330, 40));

        txtLogInPassw.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        txtLogInPassw.setForeground(new java.awt.Color(11, 22, 66));
        txtLogInPassw.setBorder(null);
        getContentPane().add(txtLogInPassw, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 335, 270, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/InicialPage.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1120, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtLogInPassw;
    private javax.swing.JTextField txtLogInUser;
    // End of variables declaration//GEN-END:variables
}
